LEARNING_RATE = 0.1
DISCOUNT_FACTOR = 0.95
EXPLORATION_RATE = 1.0
EXPLORATION_DECAY = 0.995
MIN_EXPLORATION = 0.01

REWARD_SELECTED = 10.0
REWARD_REJECTED = -1.0
REWARD_PENDING = 0.0
REWARD_STEP = 0.1

BONUS_ATS_IMPROVEMENT = 0.5
BONUS_KEYWORD_MATCH = 0.3

ATS_MILESTONES = [60, 70, 80, 90]
BONUS_ATS_MILESTONE = 2.0

REWARD_EFFICIENCY = 5.0
MAX_ITERATIONS_BONUS = 20

REWARD_NEAR_SELECTED = 2.0
NEAR_SELECTED_THRESHOLD = 5

AVAILABLE_ACTIONS = [
    "keep",
    "add_skill",
    "modify_summary",
    "quantify_experience",
    "add_keyword",
    "format_improvement",
]
